# Generated by Django 4.1.4 on 2023-05-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_resume_gender_alter_resume_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profile',
            field=models.CharField(default='profile', max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(null=True, upload_to='resumedoc/'),
        ),
    ]
