# Generated by Django 4.1.4 on 2023-05-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_resume_resume_resume_my_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='mob',
            new_name='mobile',
        ),
        migrations.AlterField(
            model_name='resume',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
