# Generated by Django 4.1.4 on 2023-05-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_mob_resume_mobile_alter_resume_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='my_file',
            new_name='resume',
        ),
    ]
